//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookDetail
    {
        public int bookId { get; set; }
        public string bookName { get; set; }
        public string Author { get; set; }
        public Nullable<int> Availability { get; set; }
    }
}
