//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerDetail
    {
        public int customerId { get; set; }
        public string customerName { get; set; }
        public string email { get; set; }
    }
}
